-- USER SQL
CREATE USER &1 IDENTIFIED BY &2;

-- QUOTAS
GRANT UNLIMITED TABLESPACE to &1;

-- ROLES
GRANT "CONNECT" TO  &1;
GRANT "RESOURCE" TO  &1;

-- SYSTEM PRIVILEGES
GRANT CREATE ANY PROCEDURE TO  &1;
GRANT CREATE ANY INDEX TO  &1;
GRANT CREATE ANY SEQUENCE TO  &1;
GRANT CREATE SESSION TO  &1;
GRANT CREATE ANY VIEW TO  &1;
GRANT CREATE ANY TRIGGER TO  &1;
GRANT CREATE ANY TABLE TO  &1;

